# Generated by Django 3.2.15 on 2022-09-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20220926_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
