# Generated by Django 4.1.1 on 2022-10-02 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0011_rename_description_uploadvideo_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='user',
        ),
        migrations.AddField(
            model_name='tweet',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='commentvideo',
            name='comment',
            field=models.CharField(max_length=275),
        ),
        migrations.AlterField(
            model_name='commentvideo',
            name='uploadedvideo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedvideo', to='tweets.uploadvideo'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=tweets.models.upload_to),
        ),
        migrations.DeleteModel(
            name='CommentImage',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='commenttweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentweet', to='tweets.tweet'),
        ),
        migrations.AddField(
            model_name='commenttweet',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
