# Generated by Django 4.1.1 on 2022-10-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_tweet_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
    ]
