# Generated by Django 4.1.1 on 2022-10-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0015_tweet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
